linters:
  disable-all: true
  enable:
    # defaults
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

    # custom
    - goheader
    - goimports
linters-settings:
  goheader:
    values:
      regexp:
        COPYRIGHT: "(© Copyright IBM Corporation 20\\d{2}(?:, 20\\d{2})?\\. All Rights Reserved\\.|\\(C\\) Copyright IBM Corp\\. 20\\d{2}\\.)"
    template-path: config/header-template.txt
issues:
  exclude-rules:
    - path: cloudantv1/cloudant_v1\.go
      linters:
        # defaults
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - structcheck
        - varcheck
        - ineffassign
        - deadcode
        - typecheck

        # custom
        - goimports
    - path: cloudantv1/cloudant_v1_suite_test\.go
      linters:
        # defaults
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - structcheck
        - varcheck
        - ineffassign
        - deadcode
        - typecheck

        # custom
        - goimports
    - path: cloudantv1/cloudant_v1_test\.go
      linters:
        # defaults
        - govet
        - errcheck
        - staticcheck
        - unused
        - gosimple
        - structcheck
        - varcheck
        - ineffassign
        - deadcode
        - typecheck

        # custom
        - goimports
