language: go

dist: xenial

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"

env:
  global:
    - GO111MODULE=on
    - SERVER_AUTH_TYPE=basic SERVER_URL=http://127.0.0.1:5984 SERVER_USERNAME=admin SERVER_PASSWORD=password

services:
  - docker

before_install:
- sudo apt-get update
# Prerequirements for semantic-release
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x
- bash scripts/setup_couch.sh

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.28.2

script:
- go test ./... -coverprofile=coverage.txt -covermode=set
- golangci-lint run

after_sucess:
- bash <(curl -s https://codecov.io/bash)

# To disable semantic-release, comment these sections.
#before_deploy:
#- pip install --user bump2version
#- npm install @semantic-release/changelog
#- npm install @semantic-release/exec
#- npm install @semantic-release/git
#- npm install @semantic-release/github

#deploy:
#- provider: script
#  script: npx semantic-release
#  skip_cleanup: true
#  on:
#    branch: master
